import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { adminDeleteContent, adminListContent, adminSaveContent } from "@/lib/admin.functions";
import { AdminPage, AdminTable, Field, inputClass, textareaClass } from "@/components/admin/AdminBits";
import { Button } from "@/components/ui/button";
import { EmptyBlock, ErrorBlock, LoadingBlock, StatusPill } from "@/components/site/Bits";

export const Route = createFileRoute("/admin/content")({ component: ContentPage });
type ContentDraft = { id?: string; content_type: "video" | "gallery" | "opinion" | "open_position" | "symposium"; title: string; slug: string; summary: string; body: string; hero_image_url: string; media_urls: string; status: "draft" | "published" };
const blank: ContentDraft = { content_type: "video", title: "", slug: "", summary: "", body: "", hero_image_url: "", media_urls: "", status: "draft" };

function ContentPage() {
  const [draft, setDraft] = useState<ContentDraft>(blank);
  const fetchContent = useServerFn(adminListContent); const saveContent = useServerFn(adminSaveContent); const deleteContent = useServerFn(adminDeleteContent); const cache = useQueryClient();
  const { data, isLoading, error } = useQuery({ queryKey: ["admin", "content"], queryFn: () => fetchContent() });
  const save = useMutation({ mutationFn: () => saveContent({ data: { ...draft, summary: draft.summary || null, body: draft.body || null, hero_image_url: draft.hero_image_url || null, media_urls: draft.media_urls.split("\n").map((url) => url.trim()).filter(Boolean), published_at: null } }), onSuccess: () => { toast.success("Content saved"); setDraft(blank); cache.invalidateQueries({ queryKey: ["admin", "content"] }); }, onError: (error: Error) => toast.error(error.message) });
  const remove = useMutation({ mutationFn: (id: string) => deleteContent({ data: { id } }), onSuccess: () => cache.invalidateQueries({ queryKey: ["admin", "content"] }), onError: (error: Error) => toast.error(error.message) });
  return <AdminPage title="Content" description="Structured videos, galleries, opinions, positions and symposium content. Articles remain in their dedicated editor.">
    {isLoading && <LoadingBlock label="Loading content" />}{error && <ErrorBlock error={error} />}{data?.length === 0 && <EmptyBlock title="No additional content yet" />}
    {data && data.length > 0 && <AdminTable head={["Type", "Title", "Status", "Updated", ""]}>{data.map((entry) => <tr key={entry.id} className="[&>td]:px-4 [&>td]:py-3"><td className="capitalize">{entry.content_type.replace(/_/g, " ")}</td><td><p className="font-medium">{entry.title}</p><p className="text-xs text-muted-foreground">/{entry.slug}</p></td><td><StatusPill tone={entry.status === "published" ? "success" : "muted"}>{entry.status}</StatusPill></td><td>{new Date(entry.updated_at).toLocaleDateString("en-GB")}</td><td className="space-x-3"><button className="text-xs underline" onClick={() => setDraft({ id: entry.id, content_type: entry.content_type, title: entry.title, slug: entry.slug, summary: entry.summary ?? "", body: entry.body ?? "", hero_image_url: entry.hero_image_url ?? "", media_urls: Array.isArray(entry.media_urls) ? entry.media_urls.filter((url): url is string => typeof url === "string").join("\n") : "", status: entry.status })}>Edit</button><button className="text-xs underline text-destructive" onClick={() => { if (confirm(`Delete ${entry.title}?`)) remove.mutate(entry.id); }}>Delete</button></td></tr>)}</AdminTable>}
    <form className="mt-10 space-y-5 border border-border bg-card p-6" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><h2 className="font-display text-lg font-bold">{draft.id ? "Edit content item" : "New content item"}</h2>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Content type"><select className={inputClass} value={draft.content_type} onChange={(event) => setDraft({ ...draft, content_type: event.target.value as typeof draft.content_type })}>{["video", "gallery", "opinion", "open_position", "symposium"].map((type) => <option key={type} value={type}>{type.replace(/_/g, " ")}</option>)}</select></Field><Field label="Status"><select className={inputClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as typeof draft.status })}><option value="draft">Draft</option><option value="published">Published</option></select></Field><Field label="Title"><input required className={inputClass} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></Field><Field label="Slug"><input required pattern="[a-z0-9-]+" className={inputClass} value={draft.slug} onChange={(event) => setDraft({ ...draft, slug: event.target.value })} /></Field></div>
      <Field label="Summary"><input className={inputClass} value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></Field><Field label="Body"><textarea rows={8} className={textareaClass} value={draft.body} onChange={(event) => setDraft({ ...draft, body: event.target.value })} /></Field><Field label="Hero image URL"><input type="url" className={inputClass} value={draft.hero_image_url} onChange={(event) => setDraft({ ...draft, hero_image_url: event.target.value })} /></Field><Field label="Media URLs" hint="One URL per line; use for videos or gallery images."><textarea className={textareaClass} value={draft.media_urls} onChange={(event) => setDraft({ ...draft, media_urls: event.target.value })} /></Field><div className="flex gap-3"><Button type="submit" variant="ink" disabled={save.isPending}>{save.isPending ? "Saving..." : "Save content"}</Button>{draft.id && <Button type="button" variant="outlineInk" onClick={() => setDraft(blank)}>New item</Button>}</div>
    </form>
  </AdminPage>;
}
