/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountEventsRouteImport } from './routes/account.events'
import { Route as AccountMembershipRouteImport } from './routes/account.membership'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSpeakersRouteImport } from './routes/admin.speakers'
import { Route as AdminWorkshopsRouteImport } from './routes/admin.workshops'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as TicketsGuestRouteImport } from './routes/tickets.guest'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as CommunityArticlesSlugRouteImport } from './routes/community.articles.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEventsRoute = AccountEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMembershipRoute = AccountMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkshopsRoute = AdminWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AdminRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsGuestRoute = TicketsGuestRouteImport.update({
  id: '/tickets/guest',
  path: '/tickets/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityArticlesSlugRoute = CommunityArticlesSlugRouteImport.update({
  id: '/community/articles/$slug',
  path: '/community/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/account/events': typeof AccountEventsRoute
  '/account/membership': typeof AccountMembershipRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/guest': typeof TicketsGuestRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/community/articles/$slug': typeof CommunityArticlesSlugRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/account/events': typeof AccountEventsRoute
  '/account/membership': typeof AccountMembershipRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/guest': typeof TicketsGuestRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/community': typeof CommunityIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/community/articles/$slug': typeof CommunityArticlesSlugRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/account/events': typeof AccountEventsRoute
  '/account/membership': typeof AccountMembershipRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/workshops': typeof AdminWorkshopsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/guest': typeof TicketsGuestRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/community/articles/$slug': typeof CommunityArticlesSlugRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/demo'
    | '/get-involved'
    | '/login'
    | '/membership'
    | '/partners'
    | '/register'
    | '/account/events'
    | '/account/membership'
    | '/account/profile'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/members'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin/workshops'
    | '/events/$slug'
    | '/tickets/guest'
    | '/account/'
    | '/admin/'
    | '/community/'
    | '/events/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/api/public/stripe-webhook'
    | '/community/articles/$slug'
    | '/admin/articles/'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/get-involved'
    | '/login'
    | '/membership'
    | '/partners'
    | '/register'
    | '/account/events'
    | '/account/membership'
    | '/account/profile'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/members'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin/workshops'
    | '/events/$slug'
    | '/tickets/guest'
    | '/account'
    | '/admin'
    | '/community'
    | '/events'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/api/public/stripe-webhook'
    | '/community/articles/$slug'
    | '/admin/articles'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/demo'
    | '/get-involved'
    | '/login'
    | '/membership'
    | '/partners'
    | '/register'
    | '/account/events'
    | '/account/membership'
    | '/account/profile'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/members'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin/workshops'
    | '/events/$slug'
    | '/tickets/guest'
    | '/account/'
    | '/admin/'
    | '/community/'
    | '/events/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/api/public/stripe-webhook'
    | '/community/articles/$slug'
    | '/admin/articles/'
    | '/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DemoRoute: typeof DemoRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  PartnersRoute: typeof PartnersRoute
  RegisterRoute: typeof RegisterRoute
  EventsSlugRoute: typeof EventsSlugRoute
  TicketsGuestRoute: typeof TicketsGuestRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  CommunityArticlesSlugRoute: typeof CommunityArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/events': {
      id: '/account/events'
      path: '/events'
      fullPath: '/account/events'
      preLoaderRoute: typeof AccountEventsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/membership': {
      id: '/account/membership'
      path: '/membership'
      fullPath: '/account/membership'
      preLoaderRoute: typeof AccountMembershipRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workshops': {
      id: '/admin/workshops'
      path: '/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminWorkshopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/guest': {
      id: '/tickets/guest'
      path: '/tickets/guest'
      fullPath: '/tickets/guest'
      preLoaderRoute: typeof TicketsGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/articles/$slug': {
      id: '/community/articles/$slug'
      path: '/community/articles/$slug'
      fullPath: '/community/articles/$slug'
      preLoaderRoute: typeof CommunityArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountEventsRoute: typeof AccountEventsRoute
  AccountMembershipRoute: typeof AccountMembershipRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountEventsRoute: AccountEventsRoute,
  AccountMembershipRoute: AccountMembershipRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminWorkshopsRoute: typeof AdminWorkshopsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactsRoute: AdminContactsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminWorkshopsRoute: AdminWorkshopsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DemoRoute: DemoRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  PartnersRoute: PartnersRoute,
  RegisterRoute: RegisterRoute,
  EventsSlugRoute: EventsSlugRoute,
  TicketsGuestRoute: TicketsGuestRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  CommunityArticlesSlugRoute: CommunityArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
